#!/usr/bin/env bash
set -e

here="$(dirname "$0")"
here="$(cd "$here"; pwd)"

echo "Installing submodules"
git submodule init
git submodule update

echo "Download package lists"
sudo apt-get update -q -y 2>&1 >/dev/null

echo "Install basic tools"
sudo apt-get install -y git make vim zsh tmux ack-grep exuberant-ctags 2>&1 >/dev/null

if [[ ! -d ~/.oh-my-zsh ]]; then
  echo "Install oh-my-zsh"
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

if [[ $SHELL != "/bin/zsh" ]]; then
  echo "Switch to zsh"
  chsh -s $(which zsh)
fi

echo "Link dotfiles"
for file in "$here"/*; do
name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  if [[ !( "install README" =~ $name || -e ~/$dotname || -d $file/.git ) ]]; then
    ln -sfv ${file#$HOME/} "${HOME}/${dotname}"
  fi
done

if [[ ! -d ~/.vim ]]; then
  echo "Install vimfiles"
  ssh-keyscan github.com >> ~/.ssh/known_hosts
  git clone git@github.com:strika/vimfiles.git ~/.vim
  cd ~/.vim && rake
fi
