[language-server.standardrb]
command = "standardrb"
args = [ "--lsp" ]

[language-server.github-copilot]
command = "copilot-language-server"
args = [ "--stdio" ]

[[language]]
name = "ruby"
language-servers = [ { name = "ruby-lsp", except-features = [ "diagnostics" ] }, "standardrb" ]

[language-server.biome]
command = "npx"
args = [ "biome", "lsp-proxy" ]

[[language]]
name = "javascript"
language-servers = [ "biome" ]

[[language]]
name = "json"
language-servers = [ "biome" ]
